# compose.prod.yaml
version: '3.8'

services:
  app:
    # 重点：我们不再使用 build，而是直接指定镜像名。
    # 这个名字将由 GitHub Actions 动态构建和推送。
    # 例如：ghcr.io/你的用户名/你的仓库名:latest
    image: ghcr.io/CaiZongyuan/fastapi_test:latest # <--- 在此填写你的镜像信息
    restart: always # 推荐生产环境使用，确保容器失败后能自动重启
    env_file:
      - .env.compose # 环境变量文件保持不变
    ports:
      - "8002:8002"
    # 重点：不再有 command 覆盖，我们将使用 Dockerfile 中的 CMD
    # 重点：不再有源码卷挂载，代码已经在镜像里了
    # 重点：不再有 develop 和 watch
    depends_on:
      db_service:
        condition: service_healthy

  db_service:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRES_USER=user_test
      - POSTGRES_PASSWORD=pw_test
      - POSTGRES_DB=MyPostgresql
    ports:
      - "5432:5432"
    volumes:
      - MyPostgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_test -d MyPostgresql"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  MyPostgresql_data: