services:
  app:
    image: fastapi_test:v1
    build: 
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env.compose
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
    # 告诉 app 服务，必须等到 db_service 的健康检查状态变成 "healthy" 之后，才能开始启动自己
    depends_on:
      db_service:
        condition: service_healthy # 等待 db_service 的健康检查通过后再启动 app
  db_service:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=user_test
      - POSTGRES_PASSWORD=pw_test
      - POSTGRES_DB=MyPostgresql
    ports:
      - "5432:5432"
    # expose:
    #   - 5432
    volumes:
      - MyPostgresql_data:/var/lib/postgresql/data
    # 给 db_service 添加了一个健康检查。每隔10秒运行 pg_isready 命令来检查 PostgreSQL 是否准备好接受连接
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_test -d MyPostgresql"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  MyPostgresql_data:
    